# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: sidekick

release:
   name_template: "Release version {{.Tag}}"
   github:
     owner: minio
     name: sidekick
   extra_files:
     - glob: "*.minisig"
     - glob: "*.zip"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath
      - --tags=kqueue

    ldflags:
      - -s -w -X github.com/minio/sidekick/pkg.ReleaseTag={{.Tag}} -X github.com/minio/sidekick/pkg.CommitID={{.FullCommit}} -X github.com/minio/sidekick/pkg.Version={{.Version}} -X github.com/minio/sidekick/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/sidekick/pkg.ReleaseTime={{.Date}}

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

nfpms:
  -
    vendor: MinIO, Inc.
    homepage: https://github.com/minio/sidekick
    maintainer: MinIO Development <dev@min.io>
    description: Sidekick is a high-performance sidecar load-balancer
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/minio/minisign.key -Sm ${artifact} < /media/${USER}/minio/minisign-passphrase'
    artifacts: all

snapshot:
  name_template: v0.0.0@{{.ShortCommit}}

changelog:
  sort: asc

dockers:
- image_templates:
  - "minio/sidekick:{{ .Tag }}-amd64"
  use_buildx: true
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "minio/sidekick:{{ .Tag }}-ppc64le"
  use_buildx: true
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/ppc64le"
- image_templates:
  - "minio/sidekick:{{ .Tag }}-s390x"
  use_buildx: true
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/s390x"
- image_templates:
  - "minio/sidekick:{{ .Tag }}-arm64"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: minio/sidekick:{{ .Tag }}
  image_templates:
  - minio/sidekick:{{ .Tag }}-amd64
  - minio/sidekick:{{ .Tag }}-arm64
  - minio/sidekick:{{ .Tag }}-ppc64le
  - minio/sidekick:{{ .Tag }}-s390x
- name_template: minio/sidekick:latest
  image_templates:
  - minio/sidekick:{{ .Tag }}-amd64
  - minio/sidekick:{{ .Tag }}-arm64
  - minio/sidekick:{{ .Tag }}-ppc64le
  - minio/sidekick:{{ .Tag }}-s390x
